const markdownUrls = {
  solana: {
    setup: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/solana/solana-setup.md',
    connect: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/solana/solana-01-connect.md',
    account: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/solana/solana-02-account.md',
    fund: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/solana/solana-03-fund.md',
    balance: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/solana/solana-04-balance.md',
    transfer: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/solana/solana-05-transfer.md',
    deploy: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/solana/solana-06-deploy.md',
    greeter: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/solana/solana-07-greeter.md',
    getter: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/solana/solana-08-getvalue.md',
    setter: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/solana/solana-09-setvalue.md',
  },
  polygon: {
    setup: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/polygon/polygon-setup.md',
    connect: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/polygon/polygon-01-connect.md',
    query: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/polygon/polygon-02-query.md',
    balance: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/polygon/polygon-04-fund.md',
    transfer: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/polygon/polygon-05-transfer.md',
    deploy: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/polygon/polygon-06-deploy.md',
    setter: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/polygon/polygon-07-setter.md',
    getter: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/polygon/polygon-08-getter.md',
    restore: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/polygon/polygon-03-restore.md',
  },
  avalanche: {
    setup: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/avalanche/avalanche-setup.md',
    connect: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/avalanche/avalanche-01-connect.md',
    account: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/avalanche/avalanche-02-account.md',
    balance: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/avalanche/avalanche-03-balance.md',
    transfer: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/avalanche/avalanche-04-transfer.md',
    export: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/avalanche/avalanche-05-export.md',
    import: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/avalanche/avalanche-06-import.md',
  },
  celo: {
    setup: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/celo/celo-setup.md',
    connect: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/celo/celo-01-connect.md',
    account: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/celo/celo-02-account.md',
    balance: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/celo/celo-03-balance.md',
    transfer: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/celo/celo-04-transfer.md',
    swap: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/celo/celo-05-swap.md',
    deploy: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/celo/celo-06-deploy.md',
    getter: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/celo/celo-07-getter.md',
    setter: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/celo/celo-08-setter.md',
  },
  polkadot: {
    setup: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/polkadot/polkadot-setup.md',
    connect: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/polkadot/polkadot-01-connect.md',
    account: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/polkadot/polkadot-02-account.md',
    restore: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/polkadot/polkadot-03-restore.md',
    estimate: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/polkadot/polkadot-04-estimate.md',
    balance: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/polkadot/polkadot-05-balance.md',
    deposit: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/polkadot/polkadot-06-deposit.md',
    transfer: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/polkadot/polkadot-07-transfer.md',
  },
  tezos: {
    setup: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/tezos/tezos-setup.md',
    connect: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/tezos/tezos-01-connect.md',
    account: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/tezos/tezos-02-account.md',
    balance: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/tezos/tezos-03-balance.md',
    transfer: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/tezos/tezos-04-transfer.md',
    deploy: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/tezos/tezos-05-deploy.md',
    getter: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/tezos/tezos-06-getter.md',
    setter: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/tezos/tezos-07-setter.md',
  },
  secret: {
    setup: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/secret/secret-setup.md',
    connect: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/secret/secret-01-connect.md',
    account: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/secret/secret-02-account.md',
    balance: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/secret/secret-03-balance.md',
    transfer: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/secret/secret-04-transfer.md',
    deploy: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/secret/secret-05-deploy.md',
    getter: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/secret/secret-06-getter.md',
    setter: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/secret/secret-07-setter.md',
  },
  near: {
    setup: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/near/near-setup.md',
    connect: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/near/near-01-connect.md',
    keypair: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/near/near-02-keypair.md',
    account: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/near/near-03-check-account.md',
    balance: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/near/near-05-balance.md',
    transfer: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/near/near-06-transfer.md',
    deploy: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/near/near-07-deploy.md',
    getter: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/near/near-08-getter.md',
    setter: 'https://raw.githubusercontent.com/figment-networks/datahub-learn/master/figment-learn/new-pathways/near/near-09-setter.md',
  },
};

module.exports = markdownUrls;
