import Head from 'next/head'
import { useRouter } from 'next/router';

import Avalanche from "components/protocols/avalanche"
import Celo from "components/protocols/celo"
import Near from "components/protocols/near"
import Polkadot from "components/protocols/polkadot";
import Polygon from "components/protocols/polygon";
import Secret from "components/protocols/secret";
import Solana from "components/protocols/solana";
import Tezos from "components/protocols/tezos";
import { CHAINS_CONFIG as CONFIG } from "lib/constants";
import { CHAINS, ChainType } from 'types/types';

export default function Chain() {
	const router = useRouter();
	const { chain } = router.query

	const protocolName = typeof chain === "string" && chain.charAt(0).toUpperCase() + chain.slice(1);

	return (
		<>
			<Head>
				<title>{`Figment Learn - ${protocolName} Pathway`}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{
				chain === CHAINS.SOLANA
					? <Solana chain={CONFIG[CHAINS.SOLANA] as ChainType} />
					: chain === CHAINS.POLYGON
						? <Polygon chain={CONFIG[CHAINS.POLYGON] as ChainType} />
						: chain === CHAINS.AVALANCHE
							? <Avalanche chain={CONFIG[CHAINS.AVALANCHE] as ChainType} />
							: chain === CHAINS.TEZOS
								? <Tezos chain={CONFIG[CHAINS.TEZOS] as ChainType} />
								: chain === CHAINS.NEAR
									? <Near chain={CONFIG[CHAINS.NEAR] as ChainType} />
									: chain === CHAINS.POLKADOT
										? <Polkadot chain={CONFIG[CHAINS.POLKADOT] as ChainType} />
										: chain === CHAINS.CELO
											? <Celo chain={CONFIG[CHAINS.CELO] as ChainType} />
											: chain === CHAINS.SECRET
												? <Secret chain={CONFIG[CHAINS.SECRET] as ChainType} />
												: null
			}
		</>
	)
}
