import Head from 'next/head'
import { useRouter } from 'next/router';

import Avalanche from "components/protocols/avalanche"
import Polygon from "components/protocols/polygon";
import Solana from "components/protocols/solana";
import { PROTOCOLS } from "components/shared/constants";
import { StepType } from 'types/types';

export default function Protocol() {
	const router = useRouter();
	const { protocol } = router.query

	const protocolName = typeof protocol === "string" && protocol.charAt(0).toUpperCase() + protocol.slice(1);

	return (
		<>
			<Head>
				<title>{`Figment Learn - ${protocolName} Pathway`}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{
				protocol === PROTOCOLS.SOLANA.id
					? <Solana steps={PROTOCOLS.SOLANA.steps as StepType[]} />
					: protocol === PROTOCOLS.POLYGON.id
						? <Polygon steps={PROTOCOLS.POLYGON.steps as StepType[]} />
						: protocol === PROTOCOLS.AVALANCHE.id
							? <Avalanche steps={PROTOCOLS.AVALANCHE.steps as StepType[]} />
							: null
			}
		</>
	)
}
