import Head from 'next/head';
import {CHAINS_CONFIG} from 'lib/constants';
import {CHAINS, ChainPropT} from 'types';
import {fetchMarkdownForChainId} from 'utils/markdown';
import WithLayoutSolana from 'components/protocols/solana';

export async function getStaticProps() {
  return {
    props: {
      chain: CHAINS_CONFIG[CHAINS.SOLANA],
      markdown: fetchMarkdownForChainId(CHAINS.SOLANA),
    },
  };
}

const Solana = (props: ChainPropT) => {
  const {chain, markdown} = props;

  return (
    <>
      <Head>
        <title>{`Figment Learn - ${chain.label} Pathway`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WithLayoutSolana chain={chain} markdown={markdown} />
    </>
  );
};

export default Solana;
